# Generated by Django 4.1 on 2023-01-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pajamanApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companyanalysis",
            options={"verbose_name_plural": "企業分析"},
        ),
    ]
