# Generated by Django 4.1 on 2023-01-27 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pajamanApp", "0003_personal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personal",
            name="user",
        ),
    ]
